name: adaptive_media_picker
description: "Adaptive Flutter media picker for images & videos with smart permissions, limited access UI, and cross-platform support (Android, iOS, Web, Desktop)."
version: 0.0.6
repository: https://github.com/jaimin-kavathia/adaptive_media_picker
issue_tracker: https://github.com/jaimin-kavathia/adaptive_media_picker/issues
documentation: https://pub.dev/documentation/adaptive_media_picker/latest/
license: MIT
topics:
  - image-picker
  - video-picker
  - camera
  - gallery
  - file-selection

environment:
  sdk: ^3.4.0
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^12.1.0
  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  permission_handler: ^12.0.1
  photo_manager: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:
